version: '3'

services:
  centreon-web:
    hostname: centreon-web
    build: ./centreon-web
    depends_on:
      - centreon-db
    environment:
      MYSQL_HOST: "centreon-db"
      MYSQL_PORT: "3306"
      MYSQL_USER: "centreon"
      MYSQL_PASSWD: "c3ntr30n"
      MYSQL_ROOT_PASSWORD: "change123"
      CENTREON_ADMIN_NAME: "Administrator"
      CENTREON_ADMIN_EMAIL: "admin@admin.co"
      CENTREON_ADMIN_PASSWD: "change123"
    ports:
      - "8080:80"
    volumes:
      - ./centreon-conf:/etc/centreon
      - ./centreon-ssh:/var/spool/centreon/.ssh
  centreon-db:
    hostname: centreon-db
    image: mariadb:10.1
    command: mysqld --open-files-limit=32000
    volumes:
      - ./centreon-db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "change123"
