#!/bin/sh

command="$1"

case $command in
    start)
        /usr/bin/supervisorctl start centengine
        ;;

    stop)
        /usr/bin/supervisorctl stop centengine
        ;;

    restart|reload)
        /usr/bin/supervisorctl restart centengine
        ;;

    status)
        /usr/bin/supervisorctl status centengine
        ;;
esac

exit 0
